""""Implement_new_pricing_model_quotas"

Revision ID: 52edbc90a8de
Revises: 816dd75fe500
Create Date: 2025-07-29 16:24:12.141225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52edbc90a8de'
down_revision = '816dd75fe500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_credits_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_credits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_credits_remaining', sa.Integer(), nullable=True))
        batch_op.drop_column('video_v2_quota_remaining')
        batch_op.drop_column('image_quota_remaining')
        batch_op.drop_column('video_v3_quota')
        batch_op.drop_column('image_quota')
        batch_op.drop_column('video_v2_quota')
        batch_op.drop_column('video_v3_quota_remaining')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_v3_quota_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('video_v2_quota', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image_quota', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('video_v3_quota', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image_quota_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('video_v2_quota_remaining', sa.INTEGER(), nullable=True))
        batch_op.drop_column('video_credits_remaining')
        batch_op.drop_column('video_credits')
        batch_op.drop_column('image_credits_remaining')
        batch_op.drop_column('image_credits')

    # ### end Alembic commands ###
