""""initial_migration"

Revision ID: 816dd75fe500
Revises: 
Create Date: 2025-07-28 18:27:34.812641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816dd75fe500'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('trial_start_date', sa.DateTime(), nullable=True),
    sa.Column('trial_end_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('quota_reset_date', sa.DateTime(), nullable=True),
    sa.Column('image_quota', sa.Integer(), nullable=True),
    sa.Column('image_quota_remaining', sa.Integer(), nullable=True),
    sa.Column('video_v2_quota', sa.Integer(), nullable=True),
    sa.Column('video_v2_quota_remaining', sa.Integer(), nullable=True),
    sa.Column('video_v3_quota', sa.Integer(), nullable=True),
    sa.Column('video_v3_quota_remaining', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('payment_method_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
