"""Add new quota columns to user model

Revision ID: a2b3c4d5e6f7
Revises: 52edbc90a8de
Create Date: 2025-07-30 17:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b3c4d5e6f7'
down_revision = '52edbc90a8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_quota', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_v2_quota', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_v3_quota', sa.Integer(), nullable=True))
        batch_op.drop_column('image_credits')
        batch_op.drop_column('video_credits_remaining')
        batch_op.drop_column('image_credits_remaining')
        batch_op.drop_column('video_credits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_credits', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image_credits_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('video_credits_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image_credits', sa.INTEGER(), nullable=True))
        batch_op.drop_column('video_v3_quota')
        batch_op.drop_column('video_v2_quota')
        batch_op.drop_column('image_quota')

    # ### end Alembic commands ###
